/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 22-May-2017 14:19:54
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2017a.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int CL3 = 17;
const float C3[17] = {
  -0.003698132234,-0.006584658287,-0.005099981558, 0.007937910035,   0.0374353826,
    0.08181903511,   0.1312061548,    0.170310989,   0.1852174997,    0.170310989,
     0.1312061548,  0.08181903511,   0.0374353826, 0.007937910035,-0.005099981558,
  -0.006584658287,-0.003698132234
};
